resources:
  jobs:
    customer_trans_onetime_ddl:
      name: customer_trans_dim_onetime_ddl
      tasks:
        - task_key: bronze_onetime_ddl
          notebook_task:
            notebook_path: /Workspace/Users/snehashrivastav@gmail.com/databricks-repo-fact/src/bronze_dim_fact_onetime_ddl
            source: WORKSPACE
        - task_key: silver_onetime_ddl
          depends_on:
            - task_key: bronze_onetime_ddl
          notebook_task:
            notebook_path: /Workspace/Users/snehashrivastav@gmail.com/databricks-repo-fact/src/silver_dim_fact_onetime_ddl
            source: WORKSPACE
        - task_key: gold_onetime_ddl
          depends_on:
            - task_key: silver_onetime_ddl
          notebook_task:
            notebook_path: /Workspace/Users/snehashrivastav@gmail.com/databricks-repo-fact/src/gold_dim_fact_onetime_ddl
            source: WORKSPACE
      queue:
        enabled: true
      performance_target: PERFORMANCE_OPTIMIZED
